<?xml version="1.0" encoding="utf-8"?><Database Name="DoAnLTUD" Class="DuLieuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PHAT\SQLEXPRESS;Initial Catalog=DoAnLTUD;Integrated Security=True" SettingsObjectName="DoAnCuoiKy.Properties.Settings" SettingsPropertyName="DoAnLTUDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.login" Member="login1s">
    <Type Name="login1">
      <Column Name="username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remme" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>